<?php

namespace Database\Seeders;

use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TitleSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $dosen = [
            'budi' => User::where('email', 'budi@ctms.com')->first(),
            'siti' => User::where('email', 'siti@ctms.com')->first(),
            'ahmad' => User::where('email', 'ahmad@ctms.com')->first(),
            'dewi' => User::where('email', 'dewi@ctms.com')->first(),
            'rudi' => User::where('email', 'rudi@ctms.com')->first(),
            'maya' => User::where('email', 'maya@ctms.com')->first(),
            'hendra' => User::where('email', 'hendra@ctms.com')->first(),
            'rina' => User::where('email', 'rina@ctms.com')->first(),
        ];

        $titles = [
            // ─── Judul Dosen — Period 1 ───────────────────────────────────
            [
                'id' => 1,
                'title' => 'Sistem Rekomendasi Produk Berbasis Collaborative Filtering',
                'description' => 'Membangun sistem rekomendasi menggunakan algoritma collaborative filtering untuk e-commerce.',
                'problem_statement' => 'Pengguna kesulitan menemukan produk yang relevan di antara ribuan pilihan.',
                'scope' => 'Backend sistem rekomendasi, integrasi dengan platform e-commerce.',
                'title_source' => 'LECTURER',
                'supervisor_approval_status' => null,
                'owner_id' => $dosen['budi']->id,
                'proposed_by_group_id' => null,
                'period_id' => 1,
                'quota' => 2,
                'is_available' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'title' => 'Deteksi Hoaks pada Media Sosial Menggunakan NLP',
                'description' => 'Sistem deteksi otomatis konten hoaks menggunakan teknik Natural Language Processing.',
                'problem_statement' => 'Penyebaran hoaks di media sosial yang sulit dideteksi secara manual.',
                'scope' => 'Model NLP, dataset berita Indonesia, API deteksi.',
                'title_source' => 'LECTURER',
                'supervisor_approval_status' => null,
                'owner_id' => $dosen['siti']->id,
                'proposed_by_group_id' => null,
                'period_id' => 1,
                'quota' => 3,
                'is_available' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'title' => 'Aplikasi Monitoring Kesehatan berbasis IoT',
                'description' => 'Platform monitoring kondisi kesehatan real-time menggunakan sensor IoT.',
                'problem_statement' => 'Kurangnya sistem monitoring kesehatan yang terjangkau dan real-time.',
                'scope' => 'Sensor IoT, backend, dashboard monitoring.',
                'title_source' => 'LECTURER',
                'supervisor_approval_status' => null,
                'owner_id' => $dosen['ahmad']->id,
                'proposed_by_group_id' => null,
                'period_id' => 1,
                'quota' => 2,
                'is_available' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'title' => 'Optimasi Rute Pengiriman Menggunakan Algoritma Genetika',
                'description' => 'Sistem optimasi rute pengiriman barang menggunakan pendekatan evolutionary algorithm.',
                'problem_statement' => 'Biaya operasional pengiriman tinggi akibat rute yang tidak optimal.',
                'scope' => 'Algoritma genetika, visualisasi rute, integrasi maps API.',
                'title_source' => 'LECTURER',
                'supervisor_approval_status' => null,
                'owner_id' => $dosen['dewi']->id,
                'proposed_by_group_id' => null,
                'period_id' => 1,
                'quota' => 2,
                'is_available' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'title' => 'Sistem Manajemen Inventori dengan Computer Vision',
                'description' => 'Otomasi manajemen stok gudang menggunakan deteksi objek berbasis computer vision.',
                'problem_statement' => 'Proses inventori manual memakan waktu dan rentan kesalahan.',
                'scope' => 'Model YOLO, sistem manajemen inventori, dashboard.',
                'title_source' => 'LECTURER',
                'supervisor_approval_status' => null,
                'owner_id' => $dosen['rudi']->id,
                'proposed_by_group_id' => null,
                'period_id' => 1,
                'quota' => 3,
                'is_available' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'title' => 'Platform E-Learning Adaptif Berbasis AI',
                'description' => 'Sistem pembelajaran online yang menyesuaikan materi berdasarkan performa dan gaya belajar.',
                'problem_statement' => 'Konten e-learning yang seragam tidak efektif untuk semua jenis pelajar.',
                'scope' => 'Algoritma adaptive learning, LMS, analitik pembelajaran.',
                'title_source' => 'LECTURER',
                'supervisor_approval_status' => null,
                'owner_id' => $dosen['maya']->id,
                'proposed_by_group_id' => null,
                'period_id' => 1,
                'quota' => 2,
                'is_available' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'title' => 'Blockchain untuk Keamanan Data Rekam Medis',
                'description' => 'Implementasi blockchain untuk menjamin integritas dan keamanan data rekam medis pasien.',
                'problem_statement' => 'Data rekam medis rentan terhadap pemalsuan dan akses tidak sah.',
                'scope' => 'Smart contract, sistem rekam medis, enkripsi data.',
                'title_source' => 'LECTURER',
                'supervisor_approval_status' => null,
                'owner_id' => $dosen['hendra']->id,
                'proposed_by_group_id' => null,
                'period_id' => 1,
                'quota' => 2,
                'is_available' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'title' => 'Chatbot Customer Service Berbasis Large Language Model',
                'description' => 'Pengembangan chatbot cerdas untuk layanan pelanggan menggunakan LLM.',
                'problem_statement' => 'Respons layanan pelanggan lambat dan tidak konsisten.',
                'scope' => 'Fine-tuning LLM, integrasi channel komunikasi, evaluasi respons.',
                'title_source' => 'LECTURER',
                'supervisor_approval_status' => null,
                'owner_id' => $dosen['rina']->id,
                'proposed_by_group_id' => null,
                'period_id' => 1,
                'quota' => 3,
                'is_available' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ─── Judul Dosen — Period 2 ───────────────────────────────────
            [
                'id' => 9,
                'title' => 'Analisis Sentimen Ulasan Produk Marketplace',
                'description' => 'Sistem analisis sentimen otomatis untuk ulasan produk di marketplace.',
                'problem_statement' => 'Merchant kesulitan memahami feedback pelanggan secara massal.',
                'scope' => 'Model sentimen, API marketplace, dashboard analitik.',
                'title_source' => 'LECTURER',
                'supervisor_approval_status' => null,
                'owner_id' => $dosen['budi']->id,
                'proposed_by_group_id' => null,
                'period_id' => 2,
                'quota' => 2,
                'is_available' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'title' => 'Sistem Prediksi Kebutuhan Energi Smart Building',
                'description' => 'Prediksi konsumsi energi gedung pintar menggunakan machine learning.',
                'problem_statement' => 'Pemborosan energi di gedung komersial akibat manajemen yang reaktif.',
                'scope' => 'Sensor energi, model prediksi, sistem kontrol otomatis.',
                'title_source' => 'LECTURER',
                'supervisor_approval_status' => null,
                'owner_id' => $dosen['siti']->id,
                'proposed_by_group_id' => null,
                'period_id' => 2,
                'quota' => 2,
                'is_available' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('titles')->insert($titles);
        $this->command->info('✅ TitleSeeder done — '.count($titles).' lecturer titles created');
    }
}
